### PR TITLE
Various changes

### LINKED ISSUE #18: Request: option to disable automatically picking up items with the offhand when the inventory is full

### LINKED ISSUE #38: Crash when right-clicking with offhand item in Et Futurum Spectator Mode
### Your GTNH Discord Username

darianstephens

### Mod Version

1.5.14

### Bug Report

In Spectator Mode, if you have an item in your offhand and right-click, the game will crash with 'Ticking Entity'.
https://pastebin.com/maw3wxxJ

### Java Version

Java 8

### Mod List or GTNH Pack Version

Et Futurum
Backhand

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.

### PR DESCRIPTION
**Pull request by Caedis**
1. Added config option for picked up items going to offhand
2. Changed configs to GTNHLib configs
3. Add null check for caused by EFR spectator mode

Fixes #18
Fixes #38

### CODE REVIEW

File: src/main/java/xonin/backhand/client/BackhandGuiConfig.java [hunk 1]
```diff
@@ -0,0 +1,17 @@
...
+import net.minecraft.client.gui.GuiScreen;
+
+import com.gtnewhorizon.gtnhlib.config.ConfigException;
+import com.gtnewhorizon.gtnhlib.config.SimpleGuiConfig;
+
+import xonin.backhand.Backhand;
+import xonin.backhand.utils.BackhandConfig;
+import xonin.backhand.utils.BackhandConfigClient;
+
+public class BackhandGuiConfig extends SimpleGuiConfig {
```
Comment (serenibyss) [inline src/main/java/xonin/backhand/client/BackhandGuiConfig.java:12]: Is this needed or is the default sufficient?

File: src/main/java/xonin/backhand/Backhand.java [hunk 2]
```diff
@@ -17,13 +19,14 @@
...
 import xonin.backhand.utils.BackhandConfig;
+import xonin.backhand.utils.BackhandConfigClient;
 
 @Mod(
     modid = Backhand.MODID,
     name = "Backhand",
     version = Tags.VERSION,
     dependencies = "required-after:gtnhlib@[0.3.2,)",
-    guiFactory = "xonin.backhand.client.gui.BackhandGuiFactory")
+    guiFactory = "backhand.client.BackhandGuiFactory")
```
Comment (serenibyss) [inline src/main/java/xonin/backhand/Backhand.java:29]: If the custom factory is needed, this seems to be missing the `xonin` package at the front

File: src/main/java/xonin/backhand/client/BackhandGuiConfig.java (hunk 1 above)
Comment (Caedis) [reply src/main/java/xonin/backhand/client/BackhandGuiConfig.java:12]: It is needed due to having 2 categories. The default only uses a single one

File: src/main/java/xonin/backhand/Backhand.java (hunk 2 above)
Comment (Caedis) [reply src/main/java/xonin/backhand/Backhand.java:29]: Works fine for me in game

File: src/main/java/xonin/backhand/client/BackhandGuiConfig.java (hunk 1 above)
Comment (Lyfts) [reply src/main/java/xonin/backhand/client/BackhandGuiConfig.java:12]: The default one uses all registered configs no matter how many categories/classes they are spread across

Comment (Caedis) [reply src/main/java/xonin/backhand/client/BackhandGuiConfig.java:12]: Ahh, good to know. Lemme try it

Comment (Caedis) [reply src/main/java/xonin/backhand/client/BackhandGuiConfig.java]: Yep, that worked. I think i forgot the register the Client class when testing it earlier

File: src/main/java/xonin/backhand/Backhand.java (hunk 2 above)
Comment (Caedis) [reply src/main/java/xonin/backhand/Backhand.java]: No longer needed

**Comment by Caedis** [comment]
@Lyfts with me using the auto gui, shouldnt I change the min GTNHLib version as well?

**Comment by Lyfts** [comment]
> @Lyfts with me using the auto gui, shouldnt I change the min GTNHLib version as well?

Ye good idea

**Review by Lyfts — APPROVED** [review]
